frr defaults traditional
hostname r1
service integrated-vtysh-config
!
router ospf
 ospf router-id 1.1.1.1
 network 10.10.1.0/24 area 0
 network 10.0.12.0/30 area 0
 network 10.0.13.0/30 area 0
!
line vty
!
