LAB_DESCRIPTION="Topologia con più LAN collegate tramite router in maglia estesa con OSPF."
LAB_VERSION=2.0
LAB_AUTHOR="Luca-Bortoluzzi"
LAB_EMAIL=luca.bortoluzzi921@edu.unito.it
LAB_WEB=http://www.kathara.org/

pc_a[0]="lan_a"
pc_a[image]="kathara/base"

pc_b[0]="lan_b"
pc_b[image]="kathara/base"

pc_c[0]="lan_c"
pc_c[image]="kathara/base"

pc_d[0]="lan_d"
pc_d[image]="kathara/base"

r1[0]="lan_a"
r1[1]="r1_r2"
r1[2]="r1_r3"
r1[image]="kathara/frr"

r2[0]="lan_b"
r2[1]="r1_r2"
r2[2]="r2_r3"
r2[3]="r2_r4"
r2[image]="kathara/frr"

r3[0]="lan_c"
r3[1]="r1_r3"
r3[2]="r2_r3"
r3[3]="r3_r4"
r3[image]="kathara/frr"

r4[0]="lan_d"
r4[1]="r2_r4"
r4[2]="r3_r4"
r4[image]="kathara/frr"
