frr defaults traditional
hostname r4
service integrated-vtysh-config
!
router bgp 65004
 bgp router-id 4.4.4.4
 no bgp ebgp-requires-policy
 no bgp network import-check
 neighbor 10.0.24.1 remote-as 65002
 neighbor 10.0.34.1 remote-as 65003
 network 10.10.4.0/24
!
line vty
!
