frr defaults traditional
hostname r4
service integrated-vtysh-config
!
router ospf
 ospf router-id 4.4.4.4
 network 10.10.4.0/24 area 0
 network 10.0.24.0/30 area 0
 network 10.0.34.0/30 area 0
 network 10.0.45.0/30 area 0
!
line vty
!
