frr defaults traditional
hostname r3
service integrated-vtysh-config
!
router bgp 65003
 bgp router-id 3.3.3.3
 no bgp ebgp-requires-policy
 no bgp network import-check
 neighbor 10.0.13.1 remote-as 65001
 neighbor 10.0.23.1 remote-as 65002
 neighbor 10.0.34.2 remote-as 65004
 network 10.10.3.0/24
!
line vty
!
