lab_name: client-router-server

description: Simple topology with a LAN and DMZ

metadata:
  description: "Multi-AS BGP topology"
  version: 2.0
  author: "Luca-Bortoluzzi"
  email: "luca.bortoluzzi921@edu.unito.it"
  web: "http://www.kathara.org/"

nodes:
  