ab_name: multi-AS

description: Topologia con più LAN collegate tramite router in maglia estesa con OSPF.

nodes:
  r1:
    type: router
    interfaces:
      - network: lan_a
        ip: 10.10.1.1/24
      - network: r1_r2
        ip: 10.0.12.1/30
      - network: r1_r3
        ip: 10.0.13.1/30
    frr:
      enabled: true
      protocol: ospf
      router_id: 1.1.1.1
      area: 0

  r2:
    type: router
    interfaces:
      - network: lan_b
        ip: 10.10.2.1/24
      - network: r1_r2
        ip: 10.0.12.2/30
      - network: r2_r3
        ip: 10.0.23.1/30
      - network: r2_r4
        ip: 10.0.24.1/30
    frr:
      enabled: true
      protocol: ospf
      router_id: 2.2.2.2
      area: 0

  r3:
    type: router
    interfaces:
      - network: lan_c
        ip: 10.10.3.1/24
      - network: r1_r3
        ip: 10.0.13.2/30
      - network: r2_r3
        ip: 10.0.23.2/30
      - network: r3_r4
        ip: 10.0.34.1/30
    frr:
      enabled: true
      protocol: ospf
      router_id: 3.3.3.3
      area: 0

  r4:
    type: router
    interfaces:
      - network: lan_d
        ip: 10.10.4.1/24
      - network: r2_r4
        ip: 10.0.24.2/30
      - network: r3_r4
        ip: 10.0.34.2/30
    frr:
      enabled: true
      protocol: ospf
      router_id: 4.4.4.4
      area: 0