LAB_DESCRIPTION="client-router-server"
LAB_VERSION=2.0
LAB_AUTHOR="Luca-Bortoluzzi"
LAB_EMAIL=luca.bortoluzzi921@edu.unito.it
LAB_WEB=http://www.kathara.org/

client[0]="lan1"
client[image]="kathara/base"

router[0]="lan1"
router[1]="dmz"
router[image]="kathara/frr"

server[0]="dmz"
server[image]="kathara/base"
